"""
Django settings for kyc project.

Generated by 'django-admin startproject' using Django 1.11.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIRNAME = os.path.abspath(os.path.dirname(__file__))
SITE_URL = 'http://app.kyc.com'
app_label = 'KYC Application'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@ez8mr!qk7x#jnl*#bf^lwbb-d^c@qb!k4n=99xq^f#lr=%cbp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.staticfiles',
	'django.contrib.postgres',
	'django_extensions',
	'pytz',
	'webpack_loader',
	'app.core',
	'app.user',
	'app.home',
	'app.authorize',
	'app.eform',
	'app.kyc',
	'app.employee',
	'app.institution',
	'app.utils'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	#'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	#'django.middleware.csrf.CsrfViewMiddleware',
	#'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	
	'app.core.middleware.KYCAuthMiddleware',  # custom Middleware
]

ROOT_URLCONF = 'kyc_app.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(DIRNAME, "../templates")],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth'
			],
		},
	},
]

WSGI_APPLICATION = 'kyc_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': 'kyc_dev',
		'USER': 'sudarshan',
		'PASSWORD': '',
		'HOST': 'localhost',
		'PORT': '5432',
		'SUPPORTS_TRANSACTIONS': True,
		'ATOMIC': False,
		'ATOMIC_REQUESTS': False,
	},
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

#STATIC_URL = '/static/'

AUTH_USER_MODEL = 'user.User'

MEDIA_ROOT = os.path.join(DIRNAME, "..", "site_media", "media")
MEDIA_URL = '/site_media/media/'



STATIC_URL = '/site_media/static/'
STATIC_ROOT = os.path.join(DIRNAME, "..", "site_media", "static")
STATICFILES_DIRS = (
	os.path.join(DIRNAME, "..", "webapp/dist"),
	os.path.join(DIRNAME, "..", "static"),
)

STATICFILES_FINDERS = (
	'django.contrib.staticfiles.finders.FileSystemFinder',
	'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)



"""

CUSTOM VALUES STARTS HERE

"""
JWT_TOKEN_VALIDITY = 6  # In Hrs
JWT_ALGORITHM = 'HS256'

ANONYMOUS_API = [
	'login',
	'verify_token',
]

SUPPORTED_API_VERSIONS = [1,2]

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': False,
        'STATS_FILE': os.path.join(DIRNAME, "..",'webapp/webpack-dev-stats.json'),
        'POLL_INTERVAL': 0.1,
        'IGNORE': ['.+\.hot-update.js', '.+\.map'],
        'BUNDLE_DIR_NAME': '/',
    }
}


PAGINATION_PER_PAGE = 20
APPEND_SLASH = False

# Local Settings
try:
	from local_settings import *
except ImportError:
	pass
