# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_relatedperson_kyc'),
        ('eform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrelatedperson',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.UserKYC'),
        ),
    ]
