# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 21:00
from __future__ import unicode_literals

import app.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('designation', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.InstitutionBranch')),
            ],
            options={
                'db_table': 'kyc_employee',
                'verbose_name': 'Employee',
            },
            bases=(models.Model, app.core.models.ModelHelperMixin),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('can_attesst', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'kyc_employee_group',
                'verbose_name': 'Employee Groups',
            },
            bases=(models.Model, app.core.models.ModelHelperMixin),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_groups',
            field=models.ManyToManyField(to='employee.EmployeeGroups'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('user', 'branch')]),
        ),
    ]
