from app.eform.serializer import CORRESPONDANCE_SERIALIZER_FIELDS,E_FORM_SERIALIZE_FIELDS,RELATED_PERSON_SERIALIZER_FIELDS


KYC_CORRESPONDANCE_SERIALIZER_FIELDS = CORRESPONDANCE_SERIALIZER_FIELDS + ['id','user']

KYC_RELATED_PERSON_SERIALIZER_FIELDS = RELATED_PERSON_SERIALIZER_FIELDS + ['id']

KYC_SERIALIZER_FIELDS = E_FORM_SERIALIZE_FIELDS + ['id','user']

KYC_DETAILED_SERIALIZER_FIELDS = E_FORM_SERIALIZE_FIELDS + ['id','user',{
	'correspondance_addresses': KYC_CORRESPONDANCE_SERIALIZER_FIELDS, 
	'related_persons': KYC_RELATED_PERSON_SERIALIZER_FIELDS, 
}]
