# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 21:00
from __future__ import unicode_literals

import app.core.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kyc_institution',
                'verbose_name': 'Institution',
            },
            bases=(models.Model, app.core.models.ModelHelperMixin),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'db_table': 'kyc_institution_branch',
                'verbose_name': 'InstitutionBranch',
            },
            bases=(models.Model, app.core.models.ModelHelperMixin),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
