AFGANISTAN_CODE = "AF"
BELGIUM_CODE = "BE"
BHUTAN_CODE = "BT"
CHINA_CODE = "CN"
INDIA_CODE = "IN"
ISRAEL_CODE = "IL"
SWEDEN_CODE = "SE"
ZIMBAWE_CODE = "ZW"

COUNTRY_CODE_LIST = (
	(AFGANISTAN_CODE, "AFGANISTAN"),
	(BELGIUM_CODE, "BELGIUM"),
	(BHUTAN_CODE, "BHUTAN"),
	(CHINA_CODE, "CHINA"),
	(INDIA_CODE, "INDIA"),
	(ISRAEL_CODE, "ISRAEL"),
	(SWEDEN_CODE, "SWEDEN"),
	(ZIMBAWE_CODE, "ZIMBAWE"),
)

ASSAM_CODE = "AS"
BIHAR_CODE = "BR"
KARNATAKA_CODE = "KA"
KERALA_CODE = "KL"
GOA_CODE = "GA"
OTHER_STATE_CODE = "XX"

INDIA_STATE_CODE_LIST = (
	(ASSAM_CODE, "Assam"),
	(BIHAR_CODE, "Bihar"),
	(KARNATAKA_CODE, "Karnataka"),
	(KERALA_CODE, "Kerala"),
	(OTHER_STATE_CODE, "Others"),
)


